---
application/{applicationId}/close:
  post:
    summary: Метод закрытия займа
    description: Метод для уведомления Сравни о закрытие займа клиентом
    parameters:
      - description: Идентификатор заявки
        in: path
        name: applicationId
        required: true
        schema:
          type: string
    requestBody:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/CloseDeal'
    responses:
      '200':
        content:
          application/json:
            schema:
              oneOf:
                - $ref: '#/components/schemas/Success'
                - $ref: '#/components/schemas/ValidationError'
    tags:
      - Методы на стороне Сравни РУ
components:
  schemas:
    CloseDeal:
      description: Закрытие займа
      properties:
        context:
          additionalProperties: false
          properties:
            closingDate:
              format: date-time
              type: string
              description: дата погашения займа
          required:
            - closingDate
          type: object
        result:
          const: success
          type: string
      required:
        - result
        - context
      title: Закрытие займа
      type: object
    Success:
      additionalProperties: false
      description: 'success'
      properties:
        context:
          type: object
        result:
          enum:
            - success
          type: string
      title: ''
      type: object
    ValidationError:
      description: 'Ошибка валидации'
      properties:
        errorDescription:
          properties:
            additional:
              type: object
            code:
              enum:
                - '00.01'
              type: string
            description:
              enum:
                - validationError
              type: string
            text:
              enum:
                - Ошибка валидации
              type: string
          type: object
        result:
          enum:
            - error
          type: string
      title: ''
      type: object