---
application/{applicationId}/confirm:
  post:
    description: Метод, для уведомления Сравни, о том что займ был выдан клиенту
    parameters:
      - description: Идентификатор заявки
        in: path
        name: applicationId
        required: true
        schema:
          type: string
    requestBody:
      content:
        application/json:
          schema:
            oneOf:
              - $ref: "#/components/schemas/Confirm"
              - $ref: "#/components/schemas/PaymentBlocked"
              - $ref: ../errors/defaultRequestError.yaml#/components/schemas/Failed
              - $ref: ../errors/defaultRequestError.yaml#/components/schemas/BlackList
              - $ref: ../errors/defaultRequestError.yaml#/components/schemas/ClientMoratorium
              - $ref: ../errors/defaultRequestError.yaml#/components/schemas/Reject
              - $ref: ../errors/defaultRequestError.yaml#/components/schemas/DocumentsRejected
    responses:
      "200":
        description:  ''
        content:
          application/json:
            schema:
              oneOf:
                - $ref: "#/components/schemas/Success"
                - $ref: ../errors/defaultRequestError.yaml#/components/schemas/ValidationError
    summary: Метод подтверждения выдачи займа
    tags:
      - Методы на стороне Сравни РУ
components:
  schemas:
    Success:
      additionalProperties: false
      description: 'success'
      properties:
        context:
          type: object
        result:
          enum:
            - success
          type: string
      title: ''
      type: object
    Confirm:
      description: Уведомление о выдаче займа
      properties:
        result:
          enum:
            - success
          type: string
        context:
          additionalProperties: false
          properties:
            createdAt:
              format: date-time
              type: string
            updatedAt:
              format: date-time
              type: string
          required:
            - createdAt
            - updatedAt
          type: object
      required:
        - result
        - context
      title: Успешная выдача займа
      type: object
    PaymentBlocked:
      description: Выплата не удалась
      properties:
        errorDescription:
          additionalProperties: false
          properties:
            additional:
              nullable: true
              type: object
            code:
              enum:
                - "03.08"
              type: string
            description:
              enum:
                - paymentBlocked
              type: string
            text:
              example: Не удалось произвести выплату
              type: string
          required:
            - code
            - description
            - text
          type: object
        result:
          enum:
            - error
          type: string
      required:
        - result
        - errorDescription
      title: Выплата не удалась
      type: object
    ValidationError:
      description: "Ошибка валидации"
      properties:
        errorDescription:
          properties:
            additional:
              type: object
            code:
              enum:
                - "00.01"
              type: string
            description:
              enum:
                - validationError
              type: string
            text:
              enum:
                - Ошибка валидации
              type: string
          type: object
        result:
          enum:
            - error
          type: string
      title: ""
      type: object
